### ISSUE TITLE
Support for other property attributes?

### ISSUE THREAD

**Issue by awright415** [jaystack/odata-v4-server#21]
I've been looking for a way to add attributes like maxLength, precision, and scale using decorators. So far, I haven't had any luck. Is there a way to do this with model classes directly, or does it require lower level solutions like a schema.json file or using odata-v4-metadata?

**Comment by lazarv** [comment]
This is now implemented in commit https://github.com/jaystack/odata-v4-server/commit/d697ad39f04483ab7c4a6db2059c1f322afe4416. Update to latest ```odata-v4-server``` version.

Use ```@Edm``` decorators to annotate the entity class. This will only affect the metadata document. No automatic business logic happens when using these decorators.
